version: '3'

tasks:
  default:
    internal: false
    silent: true
    # yamllint disable rule:line-length
    cmds:
      - 'echo -e "\n👋 Welcome to Task! To see available commands, run: task -l"'
      - 'echo -e "📝 To see instructions for a specific command run: task command-name --summary\n"'
      - task -l --sort none
    # yamllint enable rule:line-length

  up:
    desc: Start processes defined in `devenv.nix` in the background.
    internal: false
    silent: true
    cmd: devenv up -d

  down:
    desc: Stop processes defined in `devenv.nix` in the background.
    internal: false
    silent: true
    cmd: devenv processes down

  test:
    desc: Run pytest
    internal: false
    silent: true
    cmds:
      - pytest || true
      - rm -rf ./tmp
