name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Mac tests and Ubuntu tests are separated so that Ubuntu tests can
  # run on both PRs and main; and Mac tests only on main branch.
  ubuntu_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

  macos_tests:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker (macOS) with Colima
        run: |
          brew install docker docker-compose colima
          colima delete
          colima start --arch x86_64
          echo $SHELL
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
          docker --version
          curl -s --unix-socket $HOME/.colima/default/docker.sock http/_ping

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
