name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ubuntu_tests:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

        # Add a separate step to adjust permissions
      # - name: Adjust Permissions on Nix Store
      #   run: sudo mkdir /nix && sudo chown -R $USER:$USER /nix/

      # - name: Cache Nix Store
      #   uses: actions/cache@v3
      #   with:
      #     path: /nix/store
      #     key: nix-store-${{ runner.os }}-${{ hashFiles('**/shell.nix') }}
      #     restore-keys: |
      #       nix-store-${{ runner.os }}-

      # - name: Show caches packages
      #   run: ls /nix/store

      - uses: cachix/install-nix-action@v26

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

  macos_tests:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Nix Store
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('**/shell.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-

      - name: Setup Docker (macOS) with Colima
        run: |
          brew install docker docker-compose colima
          colima delete
          colima start --arch x86_64
          echo $SHELL
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
          docker --version
          curl -s --unix-socket $HOME/.colima/default/docker.sock http/_ping

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
