name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false # Prevents the matrix from failing fast
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: setup docker (macos) with Colima
        if: runner.os == 'macOS'
        run: |
          brew install docker docker-compose colima
          colima delete
          colima start --arch x86_64
          echo $SHELL
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
          docker --version
          curl -s --unix-socket $HOME/.colima/default/docker.sock http/_ping

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
