name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false # Prevents the matrix from failing fast
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      # Add a conditional step for macOS to create the Docker socket symlink
      - name: Create Docker socket symlink on macOS
        if: runner.os == 'macOS'
        run: sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
